import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useMemo } from "react";
import { useDermStore } from "@/lib/derm/store";
import { assessCase } from "@/lib/derm/logic";
import { PriorityBadge } from "@/components/PriorityBadge";
import type { PathologyCase, FollowUpTask, Priority } from "@/lib/derm/types";
import type { CaseSyncStatus } from "@/lib/derm/store";

export const Route = createFileRoute("/follow-up")({
  head: () => ({
    meta: [
      { title: "Follow-Up Safety Queue · DermPathOS" },
      {
        name: "description",
        content:
          "Accountable follow-up tasks generated from pathology results by BiopsyGraph.",
      },
    ],
  }),
  component: FollowUpPage,
});

const MARGIN_KEYWORDS = [
  "involved",
  "positive",
  "transected",
  "deep margin",
  "peripheral margin",
];

function marginRequiresTreatment(margins: string): boolean {
  const l = (margins || "").toLowerCase();
  if (!l) return false;
  if (MARGIN_KEYWORDS.some((k) => l.includes(k))) return true;
  // "not clear" is flagged; "clear" alone is safe
  if (l.includes("not clear")) return true;
  return false;
}

function riskLabel(c: PathologyCase): string | null {
  const dx = (c.diagnosis || "").toLowerCase();
  const path = (c.pathologyResult || "").toLowerCase();
  const s = `${dx} ${path}`;
  if (s.includes("melanoma")) return "High-risk pathology follow-up";
  if (s.includes("squamous") || s.includes("scc"))
    return "Treatment-tracked dermatology pathology";
  if (s.includes("basal") || s.includes("bcc"))
    return "Treatment-tracked dermatology pathology";
  return null;
}

type Bucket = "open_high" | "open_routine" | "closed";

interface QueueRow {
  c: PathologyCase;
  task: FollowUpTask;
  sync?: CaseSyncStatus;
  bucket: Bucket;
  risk: string | null;
  marginFlag: boolean;
}

function FollowUpPage() {
  const { cases, tasks, syncStatus, completeTask, loadDemoCases } =
    useDermStore();
  const navigate = useNavigate();

  const rows: QueueRow[] = useMemo(() => {
    return cases
      .map<QueueRow | null>((c) => {
        const task = tasks[c.id];
        if (!task) return null;
        const a = assessCase(c);
        const isHigh: Priority[] = ["Urgent", "High", "Moderate"];
        const bucket: Bucket =
          task.status === "Complete"
            ? "closed"
            : isHigh.includes(a.priority)
              ? "open_high"
              : "open_routine";
        return {
          c,
          task,
          sync: syncStatus[c.id],
          bucket,
          risk: riskLabel(c),
          marginFlag: marginRequiresTreatment(c.margins),
        };
      })
      .filter((r): r is QueueRow => r !== null);
  }, [cases, tasks, syncStatus]);

  const groups = useMemo(
    () => ({
      open_high: rows.filter((r) => r.bucket === "open_high"),
      open_routine: rows.filter((r) => r.bucket === "open_routine"),
      closed: rows.filter((r) => r.bucket === "closed"),
    }),
    [rows],
  );

  if (rows.length === 0) {
    return (
      <div className="mx-auto max-w-3xl px-6 py-20 text-center">
        <h1 className="font-display text-3xl font-semibold">
          Follow-Up Safety Queue
        </h1>
        <p className="mt-3 text-muted-foreground">
          No follow-up tasks yet. Submit a case from Intake, or load the demo
          dataset.
        </p>
        <div className="mt-8 flex justify-center gap-3">
          <button
            onClick={loadDemoCases}
            className="rounded-lg bg-[var(--lavender)] px-5 py-2.5 text-sm font-semibold text-primary-foreground hover:opacity-95"
          >
            Load Demo Cases
          </button>
          <Link
            to="/intake"
            className="rounded-lg border border-border px-5 py-2.5 text-sm font-semibold hover:bg-accent"
          >
            Go to Intake
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-6xl px-6 py-10">
      <div className="mb-8 flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="font-display text-3xl font-semibold">
            Follow-Up Safety Queue
          </h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Accountable follow-up tasks generated by BiopsyGraph from
            Butterbase-stored biopsy cases.
          </p>
        </div>
        <div className="flex gap-2">
          <Link
            to="/intake"
            className="rounded-lg border border-border px-4 py-2 text-sm font-semibold hover:bg-accent"
          >
            + New Case
          </Link>
          <Link
            to="/dashboard"
            className="rounded-lg bg-[var(--lavender)] px-4 py-2 text-sm font-semibold text-primary-foreground hover:opacity-95"
          >
            Action Dashboard
          </Link>
        </div>
      </div>

      <div className="mb-4 grid gap-3 sm:grid-cols-3">
        <SummaryStat
          label="Open · High priority"
          value={groups.open_high.length}
          tone="urgent"
        />
        <SummaryStat
          label="Open · Routine"
          value={groups.open_routine.length}
          tone="routine"
        />
        <SummaryStat
          label="Completed / Closed"
          value={groups.closed.length}
          tone="lavender"
        />
      </div>

      <GroupSection
        title="Open · High Priority"
        tone="urgent"
        rows={groups.open_high}
        onOpen={(id) =>
          navigate({ to: "/cases/$caseId", params: { caseId: id } })
        }
        onComplete={completeTask}
      />
      <GroupSection
        title="Open · Routine"
        tone="routine"
        rows={groups.open_routine}
        onOpen={(id) =>
          navigate({ to: "/cases/$caseId", params: { caseId: id } })
        }
        onComplete={completeTask}
      />
      <GroupSection
        title="Completed / Closed"
        tone="lavender"
        rows={groups.closed}
        onOpen={(id) =>
          navigate({ to: "/cases/$caseId", params: { caseId: id } })
        }
        onComplete={completeTask}
      />

      <p className="mt-6 text-[11px] text-muted-foreground">
        Butterbase task updates are read-only in this build. “Mark Reviewed” and
        “Mark Scheduled” are disabled pending a server-side PATCH route.
        “Mark Completed” updates local queue state only and does not write to
        Butterbase.
      </p>
    </div>
  );
}

function GroupSection({
  title,
  tone,
  rows,
  onOpen,
  onComplete,
}: {
  title: string;
  tone: "urgent" | "routine" | "lavender";
  rows: QueueRow[];
  onOpen: (caseId: string) => void;
  onComplete: (caseId: string) => void;
}) {
  if (rows.length === 0) return null;
  return (
    <section className="mb-8">
      <div className="mb-2 flex items-center gap-3">
        <span
          className={`inline-flex rounded-md px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${toneChip[tone]}`}
        >
          {title}
        </span>
        <span className="text-xs text-muted-foreground">{rows.length}</span>
      </div>
      <div className="card-clinical divide-y divide-border">
        {rows.map((r) => (
          <QueueRowCard
            key={r.c.id}
            row={r}
            onOpen={() => onOpen(r.c.id)}
            onComplete={() => onComplete(r.c.id)}
          />
        ))}
      </div>
    </section>
  );
}

function QueueRowCard({
  row,
  onOpen,
  onComplete,
}: {
  row: QueueRow;
  onOpen: () => void;
  onComplete: () => void;
}) {
  const { c, task, sync, risk, marginFlag } = row;
  const a = assessCase(c);
  const isComplete = task.status === "Complete";

  return (
    <div className="p-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={onOpen}
              className="font-display text-lg font-semibold hover:underline"
            >
              {c.patientName}
            </button>
            <PriorityBadge priority={a.priority} />
            <span
              className={`chip ${
                isComplete
                  ? "bg-[var(--routine-soft)] text-[var(--routine)]"
                  : "bg-[var(--gold-soft)] text-[var(--gold)]"
              }`}
            >
              {task.status}
            </span>
          </div>
          <div className="mt-1 text-xs text-muted-foreground">
            {c.bodySite} · Biopsy {c.biopsyDate || "—"} ·{" "}
            <span className="font-mono">{c.id}</span>
          </div>
          <div className="mt-2 grid gap-1 text-sm sm:grid-cols-2">
            <div>
              <span className="text-xs uppercase tracking-wider text-muted-foreground">
                Diagnosis
              </span>
              <div>{c.diagnosis || "—"}</div>
            </div>
            <div>
              <span className="text-xs uppercase tracking-wider text-muted-foreground">
                Required action
              </span>
              <div>{a.requiredAction}</div>
            </div>
          </div>
          <div className="mt-2 flex flex-wrap gap-2">
            {risk && (
              <span className="chip bg-[var(--high-soft)] text-[var(--high)]">
                {risk}
              </span>
            )}
            {marginFlag && (
              <span className="chip bg-[var(--urgent-soft)] text-[var(--urgent)]">
                Margin requires treatment planning
              </span>
            )}
            {sync?.graphSynced && sync?.graphVerified && (
              <span className="chip bg-[var(--lavender-soft)] text-[var(--lavender)]">
                BiopsyGraph verified
              </span>
            )}
            {sync && !sync.graphSynced && sync.mode === "butterbase_and_graph" && (
              <span className="chip bg-[var(--moderate-soft)] text-[var(--moderate)]">
                Graph sync pending
              </span>
            )}
            {sync?.rocketrideStatus === "complete" && (
              <span className="chip bg-[var(--routine-soft)] text-[var(--routine)]">
                RocketRide complete
              </span>
            )}
            {sync?.rocketrideStatus === "pending_configuration" && (
              <span className="chip bg-muted text-muted-foreground">
                RocketRide pending config
              </span>
            )}
            {sync?.rocketrideStatus === "failed" && (
              <span className="chip bg-[var(--urgent-soft)] text-[var(--urgent)]">
                RocketRide failed
              </span>
            )}
          </div>
        </div>
        <div className="flex flex-col gap-2">
          <button
            type="button"
            disabled
            title="Butterbase PATCH route not implemented"
            className="rounded-md border border-border px-3 py-1.5 text-xs font-medium opacity-50"
          >
            Mark Reviewed (dev)
          </button>
          <button
            type="button"
            disabled
            title="Butterbase PATCH route not implemented"
            className="rounded-md border border-border px-3 py-1.5 text-xs font-medium opacity-50"
          >
            Mark Scheduled (dev)
          </button>
          <button
            type="button"
            onClick={onComplete}
            disabled={isComplete}
            title="Local queue state only (no Butterbase write)"
            className="rounded-md bg-[var(--lavender)] px-3 py-1.5 text-xs font-semibold text-primary-foreground hover:opacity-95 disabled:opacity-40"
          >
            {isComplete ? "Completed" : "Mark Completed (local)"}
          </button>
        </div>
      </div>
    </div>
  );
}

const toneChip = {
  urgent: "text-[var(--urgent)] bg-[var(--urgent-soft)]",
  routine: "text-[var(--routine)] bg-[var(--routine-soft)]",
  lavender: "text-[var(--lavender)] bg-[var(--lavender-soft)]",
} as const;

function SummaryStat({
  label,
  value,
  tone,
}: {
  label: string;
  value: number;
  tone: keyof typeof toneChip;
}) {
  return (
    <div className="card-clinical p-4">
      <div
        className={`inline-flex rounded-md px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${toneChip[tone]}`}
      >
        {label}
      </div>
      <div className="mt-3 font-display text-3xl font-semibold text-foreground">
        {value}
      </div>
    </div>
  );
}
