/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as FollowUpRouteImport } from './routes/follow-up'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as ApiRocketrideHealthRouteImport } from './routes/api/rocketride/health'
import { Route as ApiDaytonaValidateCaseRouteImport } from './routes/api/daytona/validate-case'
import { Route as ApiDaytonaHealthRouteImport } from './routes/api/daytona/health'
import { Route as ApiCasesSubmitRouteImport } from './routes/api/cases/submit'
import { Route as ApiButterbaseVerifySarahRouteImport } from './routes/api/butterbase/verify-sarah'
import { Route as ApiButterbaseTestRouteImport } from './routes/api/butterbase/test'
import { Route as ApiButterbaseSubmitSarahRouteImport } from './routes/api/butterbase/submit-sarah'
import { Route as ApiButterbaseSubmitCaseRouteImport } from './routes/api/butterbase/submit-case'
import { Route as ApiBiopsygraphVerifySarahRouteImport } from './routes/api/biopsygraph/verify-sarah'
import { Route as ApiBiopsygraphVerifyCaseRouteImport } from './routes/api/biopsygraph/verify-case'
import { Route as ApiBiopsygraphSyncSarahRouteImport } from './routes/api/biopsygraph/sync-sarah'
import { Route as ApiBiopsygraphSyncCaseRouteImport } from './routes/api/biopsygraph/sync-case'
import { Route as ApiBiopsygraphListPatientsRouteImport } from './routes/api/biopsygraph/list-patients'
import { Route as ApiBiopsygraphHealthRouteImport } from './routes/api/biopsygraph/health'

const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpRoute = FollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRocketrideHealthRoute = ApiRocketrideHealthRouteImport.update({
  id: '/api/rocketride/health',
  path: '/api/rocketride/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDaytonaValidateCaseRoute = ApiDaytonaValidateCaseRouteImport.update({
  id: '/api/daytona/validate-case',
  path: '/api/daytona/validate-case',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDaytonaHealthRoute = ApiDaytonaHealthRouteImport.update({
  id: '/api/daytona/health',
  path: '/api/daytona/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCasesSubmitRoute = ApiCasesSubmitRouteImport.update({
  id: '/api/cases/submit',
  path: '/api/cases/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiButterbaseVerifySarahRoute =
  ApiButterbaseVerifySarahRouteImport.update({
    id: '/api/butterbase/verify-sarah',
    path: '/api/butterbase/verify-sarah',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiButterbaseTestRoute = ApiButterbaseTestRouteImport.update({
  id: '/api/butterbase/test',
  path: '/api/butterbase/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiButterbaseSubmitSarahRoute =
  ApiButterbaseSubmitSarahRouteImport.update({
    id: '/api/butterbase/submit-sarah',
    path: '/api/butterbase/submit-sarah',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiButterbaseSubmitCaseRoute = ApiButterbaseSubmitCaseRouteImport.update({
  id: '/api/butterbase/submit-case',
  path: '/api/butterbase/submit-case',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBiopsygraphVerifySarahRoute =
  ApiBiopsygraphVerifySarahRouteImport.update({
    id: '/api/biopsygraph/verify-sarah',
    path: '/api/biopsygraph/verify-sarah',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBiopsygraphVerifyCaseRoute =
  ApiBiopsygraphVerifyCaseRouteImport.update({
    id: '/api/biopsygraph/verify-case',
    path: '/api/biopsygraph/verify-case',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBiopsygraphSyncSarahRoute = ApiBiopsygraphSyncSarahRouteImport.update({
  id: '/api/biopsygraph/sync-sarah',
  path: '/api/biopsygraph/sync-sarah',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBiopsygraphSyncCaseRoute = ApiBiopsygraphSyncCaseRouteImport.update({
  id: '/api/biopsygraph/sync-case',
  path: '/api/biopsygraph/sync-case',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBiopsygraphListPatientsRoute =
  ApiBiopsygraphListPatientsRouteImport.update({
    id: '/api/biopsygraph/list-patients',
    path: '/api/biopsygraph/list-patients',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBiopsygraphHealthRoute = ApiBiopsygraphHealthRouteImport.update({
  id: '/api/biopsygraph/health',
  path: '/api/biopsygraph/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/follow-up': typeof FollowUpRoute
  '/intake': typeof IntakeRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/api/biopsygraph/health': typeof ApiBiopsygraphHealthRoute
  '/api/biopsygraph/list-patients': typeof ApiBiopsygraphListPatientsRoute
  '/api/biopsygraph/sync-case': typeof ApiBiopsygraphSyncCaseRoute
  '/api/biopsygraph/sync-sarah': typeof ApiBiopsygraphSyncSarahRoute
  '/api/biopsygraph/verify-case': typeof ApiBiopsygraphVerifyCaseRoute
  '/api/biopsygraph/verify-sarah': typeof ApiBiopsygraphVerifySarahRoute
  '/api/butterbase/submit-case': typeof ApiButterbaseSubmitCaseRoute
  '/api/butterbase/submit-sarah': typeof ApiButterbaseSubmitSarahRoute
  '/api/butterbase/test': typeof ApiButterbaseTestRoute
  '/api/butterbase/verify-sarah': typeof ApiButterbaseVerifySarahRoute
  '/api/cases/submit': typeof ApiCasesSubmitRoute
  '/api/daytona/health': typeof ApiDaytonaHealthRoute
  '/api/daytona/validate-case': typeof ApiDaytonaValidateCaseRoute
  '/api/rocketride/health': typeof ApiRocketrideHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/follow-up': typeof FollowUpRoute
  '/intake': typeof IntakeRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/api/biopsygraph/health': typeof ApiBiopsygraphHealthRoute
  '/api/biopsygraph/list-patients': typeof ApiBiopsygraphListPatientsRoute
  '/api/biopsygraph/sync-case': typeof ApiBiopsygraphSyncCaseRoute
  '/api/biopsygraph/sync-sarah': typeof ApiBiopsygraphSyncSarahRoute
  '/api/biopsygraph/verify-case': typeof ApiBiopsygraphVerifyCaseRoute
  '/api/biopsygraph/verify-sarah': typeof ApiBiopsygraphVerifySarahRoute
  '/api/butterbase/submit-case': typeof ApiButterbaseSubmitCaseRoute
  '/api/butterbase/submit-sarah': typeof ApiButterbaseSubmitSarahRoute
  '/api/butterbase/test': typeof ApiButterbaseTestRoute
  '/api/butterbase/verify-sarah': typeof ApiButterbaseVerifySarahRoute
  '/api/cases/submit': typeof ApiCasesSubmitRoute
  '/api/daytona/health': typeof ApiDaytonaHealthRoute
  '/api/daytona/validate-case': typeof ApiDaytonaValidateCaseRoute
  '/api/rocketride/health': typeof ApiRocketrideHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/follow-up': typeof FollowUpRoute
  '/intake': typeof IntakeRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/api/biopsygraph/health': typeof ApiBiopsygraphHealthRoute
  '/api/biopsygraph/list-patients': typeof ApiBiopsygraphListPatientsRoute
  '/api/biopsygraph/sync-case': typeof ApiBiopsygraphSyncCaseRoute
  '/api/biopsygraph/sync-sarah': typeof ApiBiopsygraphSyncSarahRoute
  '/api/biopsygraph/verify-case': typeof ApiBiopsygraphVerifyCaseRoute
  '/api/biopsygraph/verify-sarah': typeof ApiBiopsygraphVerifySarahRoute
  '/api/butterbase/submit-case': typeof ApiButterbaseSubmitCaseRoute
  '/api/butterbase/submit-sarah': typeof ApiButterbaseSubmitSarahRoute
  '/api/butterbase/test': typeof ApiButterbaseTestRoute
  '/api/butterbase/verify-sarah': typeof ApiButterbaseVerifySarahRoute
  '/api/cases/submit': typeof ApiCasesSubmitRoute
  '/api/daytona/health': typeof ApiDaytonaHealthRoute
  '/api/daytona/validate-case': typeof ApiDaytonaValidateCaseRoute
  '/api/rocketride/health': typeof ApiRocketrideHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/dashboard'
    | '/follow-up'
    | '/intake'
    | '/cases/$caseId'
    | '/api/biopsygraph/health'
    | '/api/biopsygraph/list-patients'
    | '/api/biopsygraph/sync-case'
    | '/api/biopsygraph/sync-sarah'
    | '/api/biopsygraph/verify-case'
    | '/api/biopsygraph/verify-sarah'
    | '/api/butterbase/submit-case'
    | '/api/butterbase/submit-sarah'
    | '/api/butterbase/test'
    | '/api/butterbase/verify-sarah'
    | '/api/cases/submit'
    | '/api/daytona/health'
    | '/api/daytona/validate-case'
    | '/api/rocketride/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/dashboard'
    | '/follow-up'
    | '/intake'
    | '/cases/$caseId'
    | '/api/biopsygraph/health'
    | '/api/biopsygraph/list-patients'
    | '/api/biopsygraph/sync-case'
    | '/api/biopsygraph/sync-sarah'
    | '/api/biopsygraph/verify-case'
    | '/api/biopsygraph/verify-sarah'
    | '/api/butterbase/submit-case'
    | '/api/butterbase/submit-sarah'
    | '/api/butterbase/test'
    | '/api/butterbase/verify-sarah'
    | '/api/cases/submit'
    | '/api/daytona/health'
    | '/api/daytona/validate-case'
    | '/api/rocketride/health'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/dashboard'
    | '/follow-up'
    | '/intake'
    | '/cases/$caseId'
    | '/api/biopsygraph/health'
    | '/api/biopsygraph/list-patients'
    | '/api/biopsygraph/sync-case'
    | '/api/biopsygraph/sync-sarah'
    | '/api/biopsygraph/verify-case'
    | '/api/biopsygraph/verify-sarah'
    | '/api/butterbase/submit-case'
    | '/api/butterbase/submit-sarah'
    | '/api/butterbase/test'
    | '/api/butterbase/verify-sarah'
    | '/api/cases/submit'
    | '/api/daytona/health'
    | '/api/daytona/validate-case'
    | '/api/rocketride/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DashboardRoute: typeof DashboardRoute
  FollowUpRoute: typeof FollowUpRoute
  IntakeRoute: typeof IntakeRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  ApiBiopsygraphHealthRoute: typeof ApiBiopsygraphHealthRoute
  ApiBiopsygraphListPatientsRoute: typeof ApiBiopsygraphListPatientsRoute
  ApiBiopsygraphSyncCaseRoute: typeof ApiBiopsygraphSyncCaseRoute
  ApiBiopsygraphSyncSarahRoute: typeof ApiBiopsygraphSyncSarahRoute
  ApiBiopsygraphVerifyCaseRoute: typeof ApiBiopsygraphVerifyCaseRoute
  ApiBiopsygraphVerifySarahRoute: typeof ApiBiopsygraphVerifySarahRoute
  ApiButterbaseSubmitCaseRoute: typeof ApiButterbaseSubmitCaseRoute
  ApiButterbaseSubmitSarahRoute: typeof ApiButterbaseSubmitSarahRoute
  ApiButterbaseTestRoute: typeof ApiButterbaseTestRoute
  ApiButterbaseVerifySarahRoute: typeof ApiButterbaseVerifySarahRoute
  ApiCasesSubmitRoute: typeof ApiCasesSubmitRoute
  ApiDaytonaHealthRoute: typeof ApiDaytonaHealthRoute
  ApiDaytonaValidateCaseRoute: typeof ApiDaytonaValidateCaseRoute
  ApiRocketrideHealthRoute: typeof ApiRocketrideHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-up': {
      id: '/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof FollowUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rocketride/health': {
      id: '/api/rocketride/health'
      path: '/api/rocketride/health'
      fullPath: '/api/rocketride/health'
      preLoaderRoute: typeof ApiRocketrideHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daytona/validate-case': {
      id: '/api/daytona/validate-case'
      path: '/api/daytona/validate-case'
      fullPath: '/api/daytona/validate-case'
      preLoaderRoute: typeof ApiDaytonaValidateCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daytona/health': {
      id: '/api/daytona/health'
      path: '/api/daytona/health'
      fullPath: '/api/daytona/health'
      preLoaderRoute: typeof ApiDaytonaHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases/submit': {
      id: '/api/cases/submit'
      path: '/api/cases/submit'
      fullPath: '/api/cases/submit'
      preLoaderRoute: typeof ApiCasesSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/butterbase/verify-sarah': {
      id: '/api/butterbase/verify-sarah'
      path: '/api/butterbase/verify-sarah'
      fullPath: '/api/butterbase/verify-sarah'
      preLoaderRoute: typeof ApiButterbaseVerifySarahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/butterbase/test': {
      id: '/api/butterbase/test'
      path: '/api/butterbase/test'
      fullPath: '/api/butterbase/test'
      preLoaderRoute: typeof ApiButterbaseTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/butterbase/submit-sarah': {
      id: '/api/butterbase/submit-sarah'
      path: '/api/butterbase/submit-sarah'
      fullPath: '/api/butterbase/submit-sarah'
      preLoaderRoute: typeof ApiButterbaseSubmitSarahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/butterbase/submit-case': {
      id: '/api/butterbase/submit-case'
      path: '/api/butterbase/submit-case'
      fullPath: '/api/butterbase/submit-case'
      preLoaderRoute: typeof ApiButterbaseSubmitCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/biopsygraph/verify-sarah': {
      id: '/api/biopsygraph/verify-sarah'
      path: '/api/biopsygraph/verify-sarah'
      fullPath: '/api/biopsygraph/verify-sarah'
      preLoaderRoute: typeof ApiBiopsygraphVerifySarahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/biopsygraph/verify-case': {
      id: '/api/biopsygraph/verify-case'
      path: '/api/biopsygraph/verify-case'
      fullPath: '/api/biopsygraph/verify-case'
      preLoaderRoute: typeof ApiBiopsygraphVerifyCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/biopsygraph/sync-sarah': {
      id: '/api/biopsygraph/sync-sarah'
      path: '/api/biopsygraph/sync-sarah'
      fullPath: '/api/biopsygraph/sync-sarah'
      preLoaderRoute: typeof ApiBiopsygraphSyncSarahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/biopsygraph/sync-case': {
      id: '/api/biopsygraph/sync-case'
      path: '/api/biopsygraph/sync-case'
      fullPath: '/api/biopsygraph/sync-case'
      preLoaderRoute: typeof ApiBiopsygraphSyncCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/biopsygraph/list-patients': {
      id: '/api/biopsygraph/list-patients'
      path: '/api/biopsygraph/list-patients'
      fullPath: '/api/biopsygraph/list-patients'
      preLoaderRoute: typeof ApiBiopsygraphListPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/biopsygraph/health': {
      id: '/api/biopsygraph/health'
      path: '/api/biopsygraph/health'
      fullPath: '/api/biopsygraph/health'
      preLoaderRoute: typeof ApiBiopsygraphHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  DashboardRoute: DashboardRoute,
  FollowUpRoute: FollowUpRoute,
  IntakeRoute: IntakeRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  ApiBiopsygraphHealthRoute: ApiBiopsygraphHealthRoute,
  ApiBiopsygraphListPatientsRoute: ApiBiopsygraphListPatientsRoute,
  ApiBiopsygraphSyncCaseRoute: ApiBiopsygraphSyncCaseRoute,
  ApiBiopsygraphSyncSarahRoute: ApiBiopsygraphSyncSarahRoute,
  ApiBiopsygraphVerifyCaseRoute: ApiBiopsygraphVerifyCaseRoute,
  ApiBiopsygraphVerifySarahRoute: ApiBiopsygraphVerifySarahRoute,
  ApiButterbaseSubmitCaseRoute: ApiButterbaseSubmitCaseRoute,
  ApiButterbaseSubmitSarahRoute: ApiButterbaseSubmitSarahRoute,
  ApiButterbaseTestRoute: ApiButterbaseTestRoute,
  ApiButterbaseVerifySarahRoute: ApiButterbaseVerifySarahRoute,
  ApiCasesSubmitRoute: ApiCasesSubmitRoute,
  ApiDaytonaHealthRoute: ApiDaytonaHealthRoute,
  ApiDaytonaValidateCaseRoute: ApiDaytonaValidateCaseRoute,
  ApiRocketrideHealthRoute: ApiRocketrideHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
